#!/bin/sh
# generated by ctx v0.3.4 — regenerate with 'ctx harness init'
# ctx:checksum sha256:8631757708d812492f0fe4e03451b74bade5cf7dd793c3047455a9ad4acca954
set -u
ctx harness compat --require "0.3.4" >/dev/null 2>&1 || exit 0
cat >/dev/null 2>&1 || true
ctx map --budget 2000 || {
  echo "ctx hooks: ctx map failed; run ctx index to rebuild the index." >&2
  exit 0
}
